theme: jekyll-theme-minimal
title: DeepF 数据笔记
email: ningincn@hotmail.com
description: "You Blog"  
keyword: "BY, BY Blog, 柏荧的博客, qiubaiying, 邱柏荧, iOS, Apple, iPhone"
sidebar-about-description: "说点装逼的话。。。"
