theme: jekyll-theme-minimal
title: DeepF 数据笔记
email: ningincn@hotmail.com
description: "Business Intelligence 互联网出行 北京"  
keyword: "BY, BY Blog, 柏荧的博客, qiubaiying, 邱柏荧, iOS, Apple, iPhone"
sidebar-about-description: "说点装逼的话。。。"

# Where things are
source:       .
destination:  ./_site
plugins_dir:  _plugins
layouts_dir:  _layouts
data_dir:     _data
includes_dir: _includes
